name: slack notifications

on:
  pull_request:
    types: [opened, reopened, closed]
  pull_request_review:
    types: [submitted]

jobs:
  opened:
    name: opened PRs
    if: ${{ (github.event.action == 'opened' || github.event.action == 'reopened') }}
    runs-on: ubuntu-latest
    outputs:
      message-ts: ${{ steps.slack.outputs.ts }}
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C06LRLC8PHQ"
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "PR: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\nStatus: *Needs Review*"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
  reviewed:
    name: reviewed PRs
    if: ${{ github.event.action == 'submitted' }}
    runs-on: ubuntu-latest
    needs: opened
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          update-ts: ${{ needs.opened.outputs.message-ts }}
          channel-id: "C06LRLC8PHQ"
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "PR: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\nStatus: *Reviewed*"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
  closed:
    name: closed PRs
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    needs: opened
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          update-ts: ${{ needs.opened.outputs.message-ts }}
          channel-id: "C06LRLC8PHQ"
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "PR: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\nStatus: *Closed*"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
