name: slack notify

on:
  pull_request_target:
    types: [labeled, closed]

# The steps for notifying on open and close are part of the same job
# because when there are multiple jobs, GitHub will create a status
# check for each one, even if it is skipped. This spams the check list.

jobs:
  slack:
    name: notify
    runs-on: ubuntu-latest
    steps:
      # Common steps
      - name: Restore cached message ts
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            message_ts
          key: ${{ github.head_ref }}
      - name: Determine mode
        id: mode
        run: |
          if [[ "${{ steps.cache-restore.outputs.cache-hit }}" == 'true' ]]
          then
            echo "cache hit"
          else
            echo "cache miss"
          fi
          echo "action: ${{ github.event.action }}"
          if [[ "${{ steps.cache-restore.outputs.cache-hit && github.event.action == 'closed' }}" == "true" ]]
          then
            echo "mode=close" >> $GITHUB_OUTPUT
          elif "${{ ! steps.cache-restore.outputs.cache-hit && github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'easy-review') }}" == "true"
          then
            echo "mode=open" >> $GITHUB_OUTPUT
          else
            echo "mode=skip" >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_OUTPUT

      # Steps for when a PR is closed
      - name: Read message ts from cache
        if: steps.mode.outputs.mode == 'close'
        id: read-from-cache
        run: touch message_ts && echo "ts=$(< message_ts)" >> $GITHUB_OUTPUT && cat message_ts
      - name: Send PR closed message to slack
        if: steps.mode.outputs.mode == 'close'
        id: slack-close
        uses: slackapi/slack-github-action@v1.25.0
        with:
          update-ts: ${{ steps.read-from-cache.outputs.ts }}
          channel-id: "C06LRLC8PHQ"
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "~<${{ github.event.pull_request.html_url }}>~ (closed)"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}

      # Steps for when a PR is opened/labeled.
      - name: Send PR opened message to slack
        if: steps.mode.outputs.mode == 'open'
        id: slack-open
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: "C06LRLC8PHQ"
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.event.pull_request.html_url }} (*needs review*)"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
      - name: Write message ts to cache
        if: steps.mode.outputs.mode == 'open'
        id: write-to-cache
        run: echo ${{ steps.slack-open.outputs.ts }} > message_ts
      - name: Save cached message ts
        if: steps.mode.outputs.mode == 'open'
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            message_ts
          key: ${{ github.head_ref }}
