name: slack notify

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  opened:
    name: opened PRs
    if: ${{ (github.event.action == 'opened' || github.event.action == 'reopened') }}
    runs-on: ubuntu-latest
    steps:
      - name: Send message to slack
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C06LRLC8PHQ"
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "PR: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\nStatus: *Needs Review*"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
      - name: Write message ts to cache
        id: write-to-cache
        run: echo ${{ steps.slack.outputs.ts }} > message_ts
      - name: Save cached message ts
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            message_ts
          key: ${{ GITHUB_REF }}

  closed:
    name: closed PRs
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    needs: opened
    steps:
      - name: Restore cached message ts
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            message_ts
          key: ${{ GITHUB_REF }}
      - name: Read message ts from cache
        id: read-from-cache
        run: touch message_ts && echo "ts=$(< message_ts)" >> $GITHUB_OUTPUT
      - name: Send message to slack
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          update-ts: ${{ steps.read-from-cache.ts }}
          channel-id: "C06LRLC8PHQ"
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "PR: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\nStatus: *Closed*"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
