name: slack notifications

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  opened:
    name: opened PRs
    if: ${{ (github.event.action == 'opened' || github.event.action == 'reopened') }}
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack_opened
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C06LRLC8PHQ"
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                      "type": "plain_text",
                      "text": "New PR opened :rocket:",
                      "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "Opened by:\n${{ github.event.pull_request.user.login }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": " Opened at:\n${{ github.event.pull_request.created_at }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
  closed:
    name: closed PRs
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack_closed
        uses: slackapi/slack-github-action@v1.24.0
        with:
          update-ts: ${{ steps.slack_opened.outputs.ts }}
          channel_id: "C06LRLC8PHQ"
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                      "type": "plain_text",
                      "text": "PR closed :white_check_mark:",
                      "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "Closed by:\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": " Closed at:\n${{ github.event.pull_request.closed_at }}"
                    }
                  ]
                },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"
                }
              }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
